name: Trigger Review Project

on:
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "edited", "review_requested", "review_request_removed", "closed"]
  pull_request_review:
  pull_request_review_comment:

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  trigger_project_workflow:
    uses: MetOffice/growss/.github/workflows/trigger-project-workflow.yaml@main
    secrets: inherit
